version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_PORT=11435
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
