name: News CDK Deploy Prod

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        

      - name: Set up Python      
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
        working-directory: apps/news-research

      - name: Configure AWS CLI for PROD
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        working-directory: apps/news-research

      - name: Run Docker
        run: |
          sudo service docker start
          docker info

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: apps/news-research

      - name: Install AWS CDK globally
        run: npm install -g aws-cdk

      - name: Bootstrap CDK environment and deploy to PROD
        run: |
          cdk bootstrap
          cdk deploy data-science-news-automation-prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        working-directory: apps/news-research

      - name: Upload JSON files to S3
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'llm_lib/prompts/'); do
            if [[ $file == *.json ]]; then
              s3_path="s3://data-science-news-prompts-prod/${file#llm_lib/prompts/}"
              aws s3 cp $file $s3_path
            fi
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        working-directory: apps/news-research
